### Introduction to Linear Algebra

Matrices are 2-dimensional objects that has rows and columns.

A matrix is a collection of numbers ordered in rows and columns. It is similar to tables and spreadsheets. 

Each value in the matrix is an element of the matrix put in a bracket.

Rows and columns are the two dimensions of a matrix.
Two matrices can be summed, subtracted, multiplied and be divided.

A Matrix can only contain numbers, symbols or expressions. It can be of any size.

If A = m x n => it means m rows annd n columns

In most programming languages, array start from zero rather than one

#### Scalars and Vectors

Scalars: 

A matrix with one row and one column. All numbers we know from algebra are referred to as scalars in linear algebra. They are objects with no dimensions. They have a 1 x 1 dimension

Vectors: 

They sit somewhere between scalars and matrices as they have one dimension. A vector is practically the simplest linear algebraic object. Matrix is a collection of vectors.

Types of vectors:
- Row Vectors
- Column Vectors

The number of elements a vector contains are know as the length of the vector.

Summary:

. Matrix: m x n - 2 dimensions
. Vector: m x 1 -  1 dimension
. Scalar: 1 x 1 -  0 dimension

#### Linear Algebra and Geometry

Mathematics works based on analogies. With linear algebra that is extremely relevant.

A point is the simplest object in terms of geometry. It has no direction or size. A scalar is like a point.

A vector has one dimension - like a line. It has a direction. The only way to get from a line to a plane is by crossing two lines. 2D space is defined by 2 lines. A matrix is a collection of vectors

A free online tool to play around with is a 3D vector plotter - academo.org. It allows us to create all kinds of matrices upto 3 x 3. In this way, you get a better grasp of the geometrical concept.

### Scalars, Vectors, and Matrices as Python Arrays

The simplest most flexible way to work with matrices in Python is by using arrays

In [1]:
#import the relevant libraries
import numpy as np

#### Declaring scalars, vectors and matrices

#### Scalars

In [2]:
s = 5

In [3]:
s

5

#### Vectors

In [4]:
v = np.array([5, -2, 4]) # () brackets for the np array and [] for the vector

In [5]:
v # v is a row vector

array([ 5, -2,  4])

#### Matrices

In [6]:
m = np.array([[5, 12, 6], [-3, 0, 14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

#### Data type

In [8]:
type(s) # returns the data type of a given variable

int

In [9]:
type (v) # 1D array

numpy.ndarray

In [10]:
type(m) # 2D array

numpy.ndarray

In [11]:
# if we want s to be consistent with the others, we can declare it as an array too

s_array = np.array(5)
s_array

array(5)

In [12]:
type(s_array)

numpy.ndarray

#### Data shapes

In [13]:
# shape returns the shape (diemensions) of a variable

m.shape

(2, 3)

In [14]:
v.shape # in the memory of the computer, this object has 3 elements

(3,)

In [15]:
# s.shape returns a error because int objects has no attribute 'shape'
s_array.shape

()

#### Creating a column vector

In [16]:
# reshape gives an array a new shape, without changing its data
v.reshape(1, 3) # this gives a row vector

array([[ 5, -2,  4]])

In [17]:
v.reshape(3, 1) # this gives a column vector

array([[ 5],
       [-2],
       [ 4]])

#### What is a Tensor

Tensorflow: A state of the art deep learning framework developed by google. It works with tensors

Tensor: It is the most general concept. Scalars, Vectors and Matrices are all Tensors of Rank 0, 1, 2 respectively. It is a generalization of the concepts we have seen so far.

Tensor Rank 3 => k x m x n. It can be thought of a collection of matrices.

Tensors can be stored in and arrays

#### Creating a tensor

In [18]:
m1 = np.array([[5, 12, 6], [-3, 0, 14]]) 
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [19]:
m2 = np.array([[9, 8,7], [1, 3, -5]]) 
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [20]:
# create an array
t = np.array([m1, m2])

In [21]:
t # t contains both matrices

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

#### Checking its shape

In [22]:
t.shape

(2, 2, 3)

#### Manually creating a tensor

To manually create a tensor, we need to write the line of code.

In [23]:
t_manual = np.array([[[5, 12, 6], [-3, 0, 14]], [[9, 8,7], [1, 3, -5]]])

In [24]:
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

#### Adding and Subtraction

Addition: 

1 condition: The two matrices must have the same dimensions.

In [25]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

Subtraction: Same rule apply as addition

#### Difference

In [26]:
m3 = np.array([[5, 3], [-2, 4]])
m4 = np.array([[7, -5], [3, 8]])

In [27]:
m3

array([[ 5,  3],
       [-2,  4]])

In [28]:
m4

array([[ 7, -5],
       [ 3,  8]])

In [29]:
m3 - m4

array([[-2,  8],
       [-5, -4]])

In [30]:
# Doing the same with floats

m5 = np.array([[[22.33, -4.73], [-203.14, 1200.02], [4.22, 234.10]]])
m5

array([[[  22.33,   -4.73],
        [-203.14, 1200.02],
        [   4.22,  234.1 ]]])

In [31]:
m6 = np.array([[[131.13, 448.29], [-340.21, 1.06], [30.41, 424.99]]])
m6

array([[[ 131.13,  448.29],
        [-340.21,    1.06],
        [  30.41,  424.99]]])

Subtraction of Vectors: Same rules apply. 

With vectors, we only care about the length.

#### Adding Vectors together

In [32]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([5, 4, 3, 2, 1])

In [33]:
v1 + v2

array([6, 6, 6, 6, 6])

In [34]:
# Subtraction
v1 - v2 

array([-4, -2,  0,  2,  4])

#### Errors when Adding Matrices

#### Addition of scalars

In [35]:
5 + 5

10

In [36]:
10 - 4

6

#### Addition of matrices

In order to add vectors and matrices together, their forms must match. We are not allowed to add vectors of different length and matrices with different dimensions.

In [37]:
m1 = np.array([[5, 12, 6], [-3, 0, 14]]) 
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [38]:
m3 = np.array([[5, 3], [-2, 4]])
m3

array([[ 5,  3],
       [-2,  4]])

In [39]:
m1 + m3 # the shapes are not the same. The same error we will get when we try to add 2 vectors with diferent length

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

#### Exceptions (addition with a scalar)

We can add scalars to matrices and vectors

In [40]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [41]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [42]:
v1

array([1, 2, 3, 4, 5])

In [43]:
v1 + 1

array([2, 3, 4, 5, 6])

The result has a meaning in terms of arrays but not in terms of linear algebra

In [44]:
m1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [45]:
v1 + np.array([1])

array([2, 3, 4, 5, 6])

### Transpose of a Matrix

#### Transposing Vectors

Transposing a column vector (TX) will yield in a row vector (XT). Therefore, the column vector equals the row vector tranposed.

Things to consider when transposing:
- The values are not changing or transforming; only their position is.
- Transposing the same vector twice yields the initial vector
- A 3x1 matrix transposed is a 1x3 matrix

#### Transposing Matrices

Transposing a m x n matrix becomes a n x m matrix E.g A (2 x 3) becomes AT (3 x 2).

#### Transposing matrices

In [46]:
A = np.array([[5, 12, 6], [-3, 0, 14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [47]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [48]:
B = np.array([[5, 3], [-2, 4]])
B

array([[ 5,  3],
       [-2,  4]])

In [49]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [50]:
C = np.array([[4, -5], [8, 12], [-2, 3], [19, 0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2,  3],
       [19,  0]])

In [51]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12,  3,  0]])

#### Transposing scalars

Any scalars when transposed equals itself

In [53]:
S = np.array([5])

In [54]:
S.T

array([5])

#### Transposing Vectors

In Python, 1D arrays do not get transposed

In [55]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [56]:
x.T

array([1, 2, 3])

In [57]:
x.shape

(3,)

In [58]:
x_reshaped = x.reshape(1, 3)
x_reshaped

array([[1, 2, 3]])

In [59]:
x_reshaped.T

array([[1],
       [2],
       [3]])

### Dot Product

It is the sum of the product of multiplication of 2 or more elements.

Scalar multiplication

Vector multiplication: Multiplication of two vectors produces a scalar. The condition however is that the vectors must have the same length

Types of product we can get:
1. Dot Product (inner product): This is heavily used. Also known as scalar product.  The notation is a dot. Multiplying 2 vectors will produce a scalar.
2. Tensor product(outer prodcut): Read on your own.

In [60]:
x = np.array([2, 8, -4]) 
y = np.array([1, -7, 3])

In [61]:
np.dot(x, y)

-66

In [62]:
u = np.array([0, 2, 5,8])
v = np.array([20, 3, 4, -1])

In [63]:
np.dot(u, v)

18

#### Scalar * Scalar

This produces another scalar.

In [64]:
np.dot(5, 6)

30

#### Scalar * Vector

This produces a vector with same length.

In [65]:
x

array([ 2,  8, -4])

In [66]:
5*x

array([ 10,  40, -20])

When we multiply a vector by a scalar, we get a vector with the same length. The initial scalar has been scaled 5 times. Multiplication by a scalar doesn't change the shape but only the scale of the values.

### Dot Product of Matrices

#### Scalar * Matrix

In [67]:
A = np.array([[5, 12, 6], [-3, 0, 14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [68]:
3*A

array([[15, 36, 18],
       [-9,  0, 42]])

#### Multiplying a matrix with another matrix

Condition: We can only multiply an m x n with an n x k matrix. 

Note :
1. Matrices are nothing more than a collection of vectors
2. When we have a dot product, we always multiply a row vector times a column vector.

#### Matrix * Matrix

In [69]:
#Example 1
B = np.array([[2, -1], [8, 0], [3, 0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [70]:
#Example 2
C = np.array([[-12, 5, -5, 1, 6], [6, -2, 0, 0, -3], [10, 2, 0, 8, 0], [9, -4, 8, 3, -6]])
C

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,  -3],
       [ 10,   2,   0,   8,   0],
       [  9,  -4,   8,   3,  -6]])

In [71]:
D = np.array([[6, -1], [8, -4], [2, -2], [7, 4], [-6, -9]])
D

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])

In [72]:
np.dot(C, D)

array([[-71, -48],
       [ 38,  29],
       [132,  14],
       [ 95,  57]])

### Why is Linear Algebra Useful?

In machine learning and linear regression, algorithms work using inputs, weight(coefficients) and outputs matrices

Applications used in data science

1. Vectorized code(array programming): 

The simplest and most commonly used. 
We use this whenever we are using linear algebra to compute many values simultaneously. It is much faster. The numpy library is used.

2. Image recognition: 

Here, you take a photo, feed it into the algorithm and classify it. Examples are
. MNIST dataset - the task is to classify handwritting digits
. cIFAR 10 - the task is to classify animals and vehicles.
. cIFAR 10o - where we have 100 different classify of images.

The problem is that we cannot take a photo and give it to a computer. We must design a way to convert it to numbers before feeding the computer e.g pixels.

We can use the RGB scale (Red, Green and Blue) for colored photo where the intensity of each color is 255.

To represent a colored photo in a linear algebraic form, we combine matrices to get a tensor, one for each color

3. Dimensionality reduction: 

Linear algebra provides us with fast and efficient ways to transform our initial matrix into a new matrix

E.g imagine a survey where there is a total of 50 questions. Very often, we have too many variables that are not so different. We reduce the complexity of the problem by reducing the variables.